In [9]:
a = input()
b = input()

if a == b:
    print('Hello peter')
elif a> b:
    print('Dr octopas')
else:
    print('No way home')

No way home


In [18]:
anime = ['hello','peter','how','are','you']
for a in anime:
    print(a,end = ' ')
print('\n')
for a in anime:
    print(a, len(a))

hello peter how are you 

hello 5
peter 5
how 3
are 3
you 3


In [6]:
def student(greet,*arg,**kwargs):
    print(greet)
    print(arg)
    print(kwargs)
course = ['Math','Physics','Biology']
info = {
    'name' : 'Tariq',
    'ID':14101084,
    'age':25,
    'dept':'CSE'
}
student('Hello',*course,**info)

Hello
('Math', 'Physics', 'Biology')
{'name': 'Tariq', 'ID': 14101084, 'age': 25, 'dept': 'CSE'}


In [18]:
month_days = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def is_leap(year):
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)

def days_in_month(year, month):
    if not 1 <= month <= 12:
        return 'Invalid Month'
    if month == 2 and is_leap(year):
        return 29
    return month_days[month]
print(days_in_month(2004, 12))
print(month_days)

31
[0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]


In [3]:
def combined_example(pos_only, /, standard, *, kwd_only):
    print(pos_only, standard, kwd_only)
combined_example(5,standard=4,kwd_only=5)

5 4 5


In [67]:
Country = ['AFG','AUS','BAN','IND','NZW','RSA','SRL','PAK','WI','ENG']
ICC = ['USSR']
print(Country)
print(5*'\t',len(Country))
Country.append('USA')
print(Country)
print(5*'\t',len(Country))
Country.extend(ICC)
print(Country)
# print(5*'\t',len(Country))
ICC.insert(1,'GER')
print(ICC)
# ICC.remove('GER')
# print(ICC)
# print(Country)
# Country.pop(-5)
# print(Country)
# ICC.clear()
# print(ICC)
# print(Country.index('IND',0,2))
# print(Country.count('USA'))
# Country.sort()
# print(Country)
Country.copy()

['AFG', 'AUS', 'BAN', 'IND', 'NZW', 'RSA', 'SRL', 'PAK', 'WI', 'ENG']
					 10
['AFG', 'AUS', 'BAN', 'IND', 'NZW', 'RSA', 'SRL', 'PAK', 'WI', 'ENG', 'USA']
					 11
['AFG', 'AUS', 'BAN', 'IND', 'NZW', 'RSA', 'SRL', 'PAK', 'WI', 'ENG', 'USA', 'USSR']
['USSR', 'GER']


['AFG',
 'AUS',
 'BAN',
 'IND',
 'NZW',
 'RSA',
 'SRL',
 'PAK',
 'WI',
 'ENG',
 'USA',
 'USSR']

In [77]:
#Stack
stack = [1,2,3]
stack.append(4)
print(stack)
stack.pop()
print(stack)
stack.pop()
print(stack)
stack.pop()
print(stack)
stack.pop()
print(stack)

[1, 2, 3, 4]
[1, 2, 3]
[1, 2]
[1]
[]


In [87]:
from collections import deque
queue = deque(['Eric','John','Mitchel'])
print(queue)
queue.append('Tomas')
print(queue)
queue.append("Graham")
print(queue)
queue.popleft()
print(queue)
queue.popleft()  
print(queue)

deque(['Eric', 'John', 'Mitchel'])
deque(['Eric', 'John', 'Mitchel', 'Tomas'])
deque(['Eric', 'John', 'Mitchel', 'Tomas', 'Graham'])
deque(['John', 'Mitchel', 'Tomas', 'Graham'])
deque(['Mitchel', 'Tomas', 'Graham'])


In [91]:
squares = []
for i in range(15):
    squares.append(i**2)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [122]:
print([x**2 for x in range(10)])
# print(s)
squares = list(map(lambda x: x**2, range(10)))
print(squares)
[(x,y) for x in [1,2,3] for y in [2,3,1] if (x!=y)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


[(1, 2), (1, 3), (2, 3), (2, 1), (3, 2), (3, 1)]

In [158]:
freshfruit = ['          banana', '       ajaira ', '                       passion fruit  ']
[rem.strip() for rem in freshfruit]

[(x,x**2) for x in range(5)]

vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [161]:
from math import pi
[str(round(pi,i)) for i in range(1,6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

In [10]:
import numpy as np
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [1,2,3,4],
    [1,2,3,4]
]
tr = np.transpose(matrix)
print(tr,matrix)
print(40*'*')
mul = np.multiply(matrix,tr)
print(mul)


[[1 5 1 1]
 [2 6 2 2]
 [3 7 3 3]
 [4 8 4 4]] [[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [1, 2, 3, 4]]
****************************************
[[ 1 10  3  4]
 [10 36 14 16]
 [ 3 14  9 12]
 [ 4 16 12 16]]


In [20]:
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [1,2,3,4],
    [1,2,3,4]
]
print(matrix)
print([[row[i] for row in matrix] for i in range(4)])

transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])
print(transposed)
list(zip(*matrix))

[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [1, 2, 3, 4]]
[[1, 5, 1, 1], [2, 6, 2, 2], [3, 7, 3, 3], [4, 8, 4, 4]]
[[1, 5, 1, 1], [2, 6, 2, 2], [3, 7, 3, 3], [4, 8, 4, 4]]


[(1, 5, 1, 1), (2, 6, 2, 2), (3, 7, 3, 3), (4, 8, 4, 4)]

In [ ]:
for num in range(1000000,1000050):
    for i in range(2,num):
        if num/2%i == 0:
            # print(n,' is Not Prime')
            print(num,' is not prime.  It is divisible by ',i,'.')
            break
    else:
        print(num,' is a prime Number')


In [25]:
set_test = {1,2,3,4,7,2,1,3,4,2,5,6}
print(set_test)
10 in set_test
a = set('bindia')
b = set('india')
print(a.intersection(b))

{1, 2, 3, 4, 5, 6, 7}
{'i', 'd', 'n', 'a'}


In [41]:
def Join(emp1,emp2):
    return emp1.update(emp2)
emp1 = {
    'name':'Tariq',
    'age':25,
    'city':'Dhaka'
}
emp2 = {
    'name':'Hasan',
    'age':26,
    'city':'Pabna'
}
print(emp1)
emp1['blood'] = 'o+'
# print(emp1['name'])
# sorted(emp.items())
print(emp1.items())
'name' in emp1
'Dhaka' in emp1.values()
print(emp1.update(emp2))
# print(Join(emp1,emp2))
print(emp1)
# print(emp2)

{'name': 'Tariq', 'age': 25, 'city': 'Dhaka'}
dict_items([('name', 'Tariq'), ('age', 25), ('city', 'Dhaka'), ('blood', 'o+')])
None
{'name': 'Hasan', 'age': 26, 'city': 'Pabna', 'blood': 'o+'}


In [50]:
print({x:x**10 for x in range(1,11)})


{1: 1, 2: 1024, 3: 59049, 4: 1048576, 5: 9765625, 6: 60466176, 7: 282475249, 8: 1073741824, 9: 3486784401, 10: 10000000000}


In [2]:
tup = ('physics', 'chemistry', 1997, 2000, 1)
print(tup)

('physics', 'chemistry', 1997, 2000, 1)


In [51]:
dict(
    name = 'Tariq',
    age = 25,
    city = 'Dhaka'
)

{'name': 'Tariq', 'age': 25, 'city': 'Dhaka'}

In [60]:
alp = {'a':'quick','brown':'fox','jump':'over','the':'net'}
for x,y in alp.items():
    print(x,y)

a quick
brown fox
jump over
the net


In [67]:
ans = {'Tariq',25,'Dhaka'}
ques = {'name','age','city'}
for q,a in zip(ques,ans):
    print(f'what is your {q}? it is {a}')

what is your age? it is 25
what is your city? it is Dhaka
what is your name? it is Tariq


In [71]:
for x,y in enumerate(['tic','tac','toe']):
    print(x,y)


0 tic
1 tac
2 toe


In [2]:
def fib(n):
    a,b = 0,1
    while a<n:
        print(a,end=' ')
        a,b = b,a+b
fib(50)

0 1 1 2 3 5 8 13 21 34 

In [9]:
def ask_ok_no(prompt, retries = 4, reminder = 'Please try again'):
    while True:
        ok = input(prompt)
        if ok in ('y','ye','yes'):
            return True
        elif ok in ('n','nop','nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('Invalid response')
        print(reminder)

In [21]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")

parrot(100)                                          # 1 positional argument
parrot(voltage=1000)                                  # 1 keyword argument
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments
parrot(action='VOOOOOM', voltage=1000000)             # 2 keyword arguments
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword

-- This parrot wouldn't voom if you put 100 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !
-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


In [ ]:
def f(a,l = []):
    l.append(a)
    return l
f(1)
f(2)
f(3)

In [ ]:
i = 5
def f(arg=i):
    print(arg)
i = 6
f()

In [ ]:
def fib2(n):
    list_r = []
    a,b = 0,1
    while a < n:
        list_r.append(a)
        a,b = b,a+b
    return list_r
fibo = fib2(int(input()))
print(fibo)

In [30]:
def function(a,x):
    return a*x

print(function(5,6))

30


In [33]:
def cheeseshop(kind,*arguments, **keywords):
    print('Do u have any ',kind, '?')
    print('I am sorry, we are all out of ',kind)
    for arg in arguments:
        print(arg)
    print('_' * 40)
    for kw in keywords:
        print(kw,' : ',keywords[kw])

cheeseshop('Limburger', 'It''s very runny, sir.', 'It''s really very, VERY runny, sir.', shopkeeper="Michael Palin", client="John Cleese", sketch="Cheese Shop Sketch")

Do u have any  Limburger ?
I am sorry, we are all out of  Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
________________________________________
shopkeeper  :  Michael Palin
client  :  John Cleese
sketch  :  Cheese Shop Sketch


In [11]:
def thunderrun(army, *tanks, **airs):
    print('What type of army a/an', army, 'is?')
    print('Is there any ', army, ' out there')
    for tank in tanks:
        print(tank)
    print(40*'*')
    for air in airs:
        print(air,':',airs[air])

thunderrun('Paladin','T90-MBT','Elite_Tos-15', 'BTR-IFV', 'Ajaira', wasted='Nothing',name='Apache', mode= 'Air to Air & Air to Ground', range= '250++', speed=4200)

What type of army a/an Paladin is?
Is there any  Paladin  out there
T90-MBT
Elite_Tos-15
BTR-IFV
Ajaira
****************************************
wasted : Nothing
name : Apache
mode : Air to Air & Air to Ground
range : 250++
speed : 4200


In [35]:
Student = {
    'name':'Tariq',
    'id':'14101084',
    'dept':'CSE',
    'course':['Math','Physics', 'CompSci','Database']
    }
# print(Student.get('course','Not_Found'))
# print(Student.items())
for key,value in Student.items():
    print(key,'=',value)

name = Tariq
id = 14101084
dept = CSE
course = ['Math', 'Physics', 'CompSci', 'Database']


In [88]:
num = [1,2,3,4,5]
for n in num:
    for l in 'abcd':
        if l == 'c':
            print('Break time')
            continue
        print(n,l)
for i in range(1,10):
    if i == 3:
        print('found!')
        break
    print(i)


found!


In [97]:

def funcc(**ke):
    for k in ke:
        print(k,':',ke[k])
funcc(name = 'Tariq',
    id='14101084',
    dept='CSE', 
    batch=35,
    course=['Math','Physics', 'CompSci','Database']
    )

def std():
    Student = {
    'name':'Tariq',
    'id':'14101084',
    'dept':'CSE'
    }
    return Student
std()


name : Tariq
id : 14101084
dept : CSE
batch : 35
course : ['Math', 'Physics', 'CompSci', 'Database']


{'name': 'Tariq', 'id': '14101084', 'dept': 'CSE'}

In [101]:
import math
# for i in reversed(range(-5,10,2)):
    # print(i)
    #math.isnan(i)

bucket = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
nai = []
for t in bucket:
    if not math.isnan(t):
        nai.append(t)
print(nai)

[56.2, 51.7, 55.3, 52.5, 47.8]


In [ ]:
for i in range(9,15):
    for n in range (2,i):
        if i%n == 0:
            #print(i, 'is not Prime Number',i,' equals', n,'*',i//n)
            break
    else:
        print(i,' is a prime number')



In [103]:
def fib2(n):   # return Fibonacci series up to n
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)
        a, b = b, a+b
    return result
fib2(5)

[0, 1, 1, 2, 3]

In [104]:
def fib1(n):
    res = []
    a,b = 0,1
    while(a<n):
        res.append(a)
        a,b = b,a+b
    return res
fib1(5)

[0, 1, 1, 2, 3]

In [119]:
yes_votes = 42572654
no_votes = 43132495
percentage = yes_votes / (yes_votes + no_votes)
# '{:-9} YES votes  {:2.2%}'.format(yes_votes, percentage)
print(f'{yes_votes} YES votes {percentage:2.2%}')


42572654 YES votes 49.67%


In [131]:
s = 'Hello World'
print(str(s))
repr(s)
str(1/7)+str('0001')
x = 10 * 3.25
y = 200 * 200
s = 'The value of x is ' + repr(x) + ', and y is ' + repr(y) + '...'
print(s)
hello = 'hello, world\n'
hellos = repr(hello)
print(hello)
repr((x, y, ('spam', 'eggs')))

Hello World
The value of x is 32.5, and y is 40000...
hello, world



"(32.5, 40000, ('spam', 'eggs'))"

In [148]:
std = {'Tariq':'Dhaka','Hasan':'Pabna'}
for name,city in std.items():
    print(f'Name : {name:10} city : {city:10}')
print('Tariq:{Tariq} Hasan:{Hasan}'.format(**std))

print('this is the story of {0}, {1} and {2}'.format('John','Abo','henry'))

Name : Tariq      city : Dhaka     
Name : Hasan      city : Pabna     
Tariq:Dhaka Hasan:Pabna
this is the story of John, Abo and henry


In [158]:
for i in range(1,10):
    print('{0:1d}{1:4d}{2:11d}'.format(i,i*i,i**i))

1   1          1
2   4          4
3   9         27
4  16        256
5  25       3125
6  36      46656
7  49     823543
8  64   16777216
9  81  387420489


In [3]:
import os
dir_fd = os.open('test', os.O_RDONLY)
def opener(path, flags):
    return os.open(path, flags, dir_fd=dir_fd)

# with open('spamspam.txt', 'w', opener=opener) as f:
#     print('This will be written to somedir/spamspam.txt', file=f)

# os.close(dir_fd)  # don't leak a file descriptor

In [43]:
with open ('test') as f:
    for line in f:
        print(line, end='')
        # te = list(f)
        # print(40*'*')
        # print(rl)
    # print(te)
f.close()

def fib0(n):
    a,b=0,1
    while(a<n):
        print(a,end=' ')
        a,b = b,a+b
        print()

def fib1(n):
    res = []
    a,b = 0,1
    while(a<n):
        res.append(a)
        a,b = b,a+b
    return res
fib1(5)

In [49]:
import time

def timer(t):
    while t!=0:
        min,sec = divmod(t,60)
        timer = '{:02d}:{:02d}'.format(min,sec)
        print('Times remaining ',timer)
        time.sleep(1)
        t -=1
        # print()

t = input("Enter the time in seconds: ")
timer(int(t))

Times remaining  00:05
Times remaining  00:04
Times remaining  00:03
Times remaining  00:02
Times remaining  00:01


In [309]:
f = open('test','r')
print(f.read())
# f.write('Hello World')
value = ('The answer',42)
s = str(value)
print(s)
# f.write(s)
# f.close()

Hello World('The answer', 42)
('The answer', 42)


In [336]:
# f = open('test','r+')
# f.write('0987654321')
# f.seek(-3, 2)
# f.read()

In [18]:
import json

f = open('test','r+')
x = [1,'simple','list']
# json.dumps(x)
json.dump(x,f)
# x = json.load(f)
print(x)


[1, 'simple', 'list']


In [5]:
with open('test','r+') as ff:
    ff.read()


In [26]:
while True:
    try:
        x = int(input('Insert a number'))
        break
        
    except ValueError:
        print('Opps!! wrong input')

Opps,  
Opps,  
Opps,  
Opps,  
Opps,  


In [4]:
a = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOxcCOHQmH7KU5rm0DZ51Xmt0+t/0nNXOoJSYq+rb3/8AGtRtMXyapwONmGI1ACJFtIG5ngRBnn+885mO77fgPXEcCLz8GO7q8ChiyFNNwJBEdx7h4WDnQCN1S3+JYkjRDebAUBohde8Z0V8zS85JYKJPBJA6ift48JLNkMZBzfb0keZZPHKFXnPTafbPYTLRpF+LbqilAjaF/dsATavsiuwYqIO05UYoSPQTqey0+z93bauqG/yKn3Oif5UxBSCzlrh3IiF2v0PlTmiY4j421eaZbMw9yLj30HyNsIQ2TeGPzoX058izslMCDfo7LIJo47ZvjbFY98p9xygjPhjrxCeM9QmqKmtx1kw4zZbXiv3eSxwD8IFZJpdnes1GPSn02sMsKU2ASGc2kmGyobpgZ0zrB+VSzLH5mJGd713C6MEZcHk+UHZyIn/2dfBGwtNh6Fmoi8F8Bf4XPW0e5tIATneN1FWoHYrIPTvO7bBG0K8M/wnnazJlTUIsnAeJNx+ZgcJY+RjAb7+tEv9VJmUYw5NPt3aIEkkE8TeVjT1KclRZ8TxnWTz+7yFiAd42pu9QMK+HlJKJ46Al4r0ImtwlQj92jbXZXfL6auNFV++pxkh0/9RAhoqpyCL5P3b4RTW4Gum7Jt3vL9evLPH0uv6FVpzhbF4zP4QeBjE9uoSTKEQ== fariha.elahee@mulytic.io'
b = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOxcCOHQmH7KU5rm0DZ51Xmt0+t/0nNXOoJSYq+rb3/8AGtRtMXyapwONmGI1ACJFtIG5ngRBnn+885mO77fgPXEcCLz8GO7q8ChiyFNNwJBEdx7h4WDnQCN1S3+JYkjRDebAUBohde8Z0V8zS85JYKJPBJA6ift48JLNkMZBzfb0keZZPHKFXnPTafbPYTLRpF+LbqilAjaF/dsATavsiuwYqIO05UYoSPQTqey0+z93bauqG/yKn3Oif5UxBSCzlrh3IiF2v0PlTmiY4j421eaZbMw9yLj30HyNsIQ2TeGPzoX058izslMCDfo7LIJo47ZvjbFY98p9xygjPhjrxCeM9QmqKmtx1kw4zZbXiv3eSxwD8IFZJpdnes1GPSn02sMsKU2ASGc2kmGyobpgZ0zrB+VSzLH5mJGd713C6MEZcHk+UHZyIn/2dfBGwtNh6Fmoi8F8Bf4XPW0e5tIATneN1FWoHYrIPTvO7bBG0K8M/wnnazJlTUIsnAeJNx+ZgcJY+RjAb7+tEv9VJmUYw5NPt3aIEkkE8TeVjT1KclRZ8TxnWTz+7yFiAd42pu9QMK+HlJKJ46Al4r0ImtwlQj92jbXZXfL6auNFV++pxkh0/9RAhoqpyCL5P3b4RTW4Gum7Jt3vL9evLPH0uv6FVpzhbF4zP4QeBjE9uoSTKEQ== fariha.elahee@mulytic.io'
a == b




c = 'fariha:$6$avejq03Iah9ejX6a$G3UdMRhwft0e8b4Tk2SxTmXdxG5nv2AbigymsLKjp3u/FARtCW9yXrBzgG/39w55yP7TScDzUxD8hfUnrmf6g.'
d = 'fariha:$6$avejq03Iah9ejX6a$G3UdMRhwft0e8b4Tk2SxTmXdxG5nv2AbigymsLKjp3u/FARtCW9yXrBzgG/39w55yP7TScDzUxD8hfUnrmf6g.'

c == d

True

In [7]:
class B(Exception):
    pass

class C(B):
    pass

class D(C):
    pass

for cls in [B, C, D]:
    try:
        raise cls()
    except D:
        print("D")
    except C:
        print("C")
    except B:
        print("B")

B
C
D


In [21]:
class Aa:
    x1 = 'This is AA'
class Ab(Aa):
    x2 = 'This is BB'
class Ac(Ab):
    x3 = 'This is CC'
class Ad(Ac):
    x4 = 'This is DD'

aa = Aa
bb = Ab
cc = Ac
dd = Ad
print(dd.x1)

This is AA


In [45]:
class fibo:
    a,b = 0,1
    while a < n:
        print(a,end=' ')
        a,b = b,a+b
n = int(input())
# Fi = fibo()
# print(n)


0 1 1 2 3 5 8 13 

In [46]:
import sys

try:
    f = open('myfile.txt')
    s = f.readline()
    i = int(s.strip())
except OSError as err:
    print("OS error: {0}".format(err))
except ValueError:
    print("Could not convert data to an integer.")
except:
    print("Unexpected error:", sys.exc_info()[0])
    raise

OS error: [Errno 2] No such file or directory: 'myfile.txt'


In [3]:
pp = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDyEF8PqDdswiE+amvIotj/ATylFLSXM2lzV0Lf72Clfv3Hmm99IqaVdMzOcOokl3jlrVB6533A1+NNZcnvDJ3C4XMrTYzKWGxSKnMLJGR2sLJdKIedLho7vMZO92K1abUQqiiWzV1sudDuLPkfwvK7T7eiivibr+UUb614LPZBSH0Uq8FQBrQ8ZljRdwYd55NVZ8gUtp81IE8Q+cHSaMh4zd4Gjz6iKNIIa6jf5lcntMMcnrzmQvpFa8iVbtSnGMIVWzgKRWxCx09IX/bjBBHUMYy6QCM0rL4MckUabHivIbUBoUyX5vC+EtfGOu7uFT8yXcs+YD6rTGctm8f60TfWerrdLQ5U9BKHg1T3ahDPUgxb2mQmv/o5joIczBA6xWZqqCNvS3UErYGpkjvB3Gq5viUQ9z3rcs3DEXgHxrzuc6ws+x9HvINj8CARmvAxRlNV5B4l50/aMb44ns5CPlEykt0z5obb54lLe1HtziDqYQouUpU3pFx5SRw2e+7sDPK94qEcgges90q439CwtFzTH6+OtVyIyHYTtDPEf7jlFnQDJW9T7T9H0WpdeYExFcEjVOma0gtt2iNJMpdoMyAj7bFtGXJgiIup6AVYO3HSrN1f12BrwNVJAGxZh9qdB9pEJPjayrT0aOJCSSXYJxKl08mazT/o7oTmmXxpHZJcXw== pranta.saha@mulytic.io'
pa = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDyEF8PqDdswiE+amvIotj/ATylFLSXM2lzV0Lf72Clfv3Hmm99IqaVdMzOcOokl3jlrVB6533A1+NNZcnvDJ3C4XMrTYzKWGxSKnMLJGR2sLJdKIedLho7vMZO92K1abUQqiiWzV1sudDuLPkfwvK7T7eiivibr+UUb614LPZBSH0Uq8FQBrQ8ZljRdwYd55NVZ8gUtp81IE8Q+cHSaMh4zd4Gjz6iKNIIa6jf5lcntMMcnrzmQvpFa8iVbtSnGMIVWzgKRWxCx09IX/bjBBHUMYy6QCM0rL4MckUabHivIbUBoUyX5vC+EtfGOu7uFT8yXcs+YD6rTGctm8f60TfWerrdLQ5U9BKHg1T3ahDPUgxb2mQmv/o5joIczBA6xWZqqCNvS3UErYGpkjvB3Gq5viUQ9z3rcs3DEXgHxrzuc6ws+x9HvINj8CARmvAxRlNV5B4l50/aMb44ns5CPlEykt0z5obb54lLe1HtziDqYQouUpU3pFx5SRw2e+7sDPK94qEcgges90q439CwtFzTH6+OtVyIyHYTtDPEf7jlFnQDJW9T7T9H0WpdeYExFcEjVOma0gtt2iNJMpdoMyAj7bFtGXJgiIup6AVYO3HSrN1f12BrwNVJAGxZh9qdB9pEJPjayrT0aOJCSSXYJxKl08mazT/o7oTmmXxpHZJcXw== pranta.saha@mulytic.io'

pp == pa


la = 'pranta:$6$yd9hfZIXiINbL4hq$AROfpv.qlLEM9ZoDLLcQOWuGHF55Sj721opIgvxTdAa2JM4GWx88BRb0qth2/OhZIyctry8mY6xPj92RM6Nc30'
lb = 'pranta:$6$yd9hfZIXiINbL4hq$AROfpv.qlLEM9ZoDLLcQOWuGHF55Sj721opIgvxTdAa2JM4GWx88BRb0qth2/OhZIyctry8mY6xPj92RM6Nc30'

la == lb

True

In [5]:
while True:
    try:
        x = int(input('Please enter a number: '))
        print(x)
        break
    except:
        print(ValueError)




3


In [11]:
try:
    raise Exception('spam', 'eggs','Hello')
except Exception as inst:
    # print(type(inst))    # the exception instance
    # print(inst.args)     # arguments stored in .args
    # print(inst)          # __str__ allows args to be printed directly,
                         # but may be overridden in exception subclasses
    x, y ,z= inst.args     # unpack args
    print('x =', x)
    print('y =', y)
    print('z =', z)


x = spam
y = eggs
z = Hello


In [35]:
# i = 'hello_world'
x = 0
while x < 6:
  x += 1
  if x == 6:
    break
  print(x)

1
2
3
4
5


In [ ]:
import filecmp
import difflib

f1 = open('file_1.txt')
f2 = open('file_2.txt')
print(filecmp.cmp('file_1.txt','file_2.txt'))



# with open('file_1.txt') as file_1:
#     file_1_txt = file_1.readlines

# with open('file_2.txt') as file_2:
#     file_2_txt = file_2.readlines

# for line in file_1_txt,file_2_txt:
    

# Importing difflib

with open('file_1.txt') as file_1:
	file_1_text = file_1.readlines()

with open('file_2.txt') as file_2:
	file_2_text = file_2.readlines()

# Find and print the diff:
for line in difflib.unified_diff(
		file_1_text, file_2_text, fromfile='file_1.txt',
		tofile='file_2.txt', lineterm=''):
	print(line)



In [4]:
x = [1,2,3,4,5]
if 6 in x:
    print('found')
else:
    print(False)
# print(x)

False


In [12]:
import calendar
import datetime

numb = calendar.monthrange(2028,2)[1]
print(numb)
wday = calendar.weekday(2022, 12, 6)
print(wday)


29
1


In [ ]:
from calendar import monthrange
from sys import argv
year = argv[0]
month = argv[1]

num_days = monthrange(year,month)[1]

print(num_days)

In [11]:
from datetime import datetime

date_time_str = '2022-03-22 01:55:19'
date_time_str1 = '2022-03-22'

date_time_obj = datetime.strptime(date_time_str, '%Y-%m-%d %H:%M:%S')
date_time_obj1 = datetime.strptime(date_time_str1, '%Y-%m-%d')


print ("The date is", date_time_obj)
print ('The date is {:%Y-%m-%d}'.format(date_time_obj1))
print (f'The date is {date_time_obj1:%Y-%m-%d}')

The date is 2022-03-22 01:55:19
The date is 2022-03-22
The date is 2022-03-22


In [3]:
import requests
r = requests.get('https://xkcd.com/353/')
# print(r.content)
with open ('file_content.txt','w') as f:
    f.write(r.text)
    # print(f)

In [14]:
with open('recognized.txt','r') as f:
    # print(f.readline())
    text_size = 10
    content = f.read(text_size)
    print(content)
    f.seek(0)
    print(content)
    # for line in f:
    #     print(line,end='')

this is a 
this is a 


In [16]:
with open('file_content.txt','r') as rf:
    with open('file_copy1.txt','w') as wf:
        # wf.write(rf.read())
        for line in rf:
            wf.write(line)

In [ ]:
import requests

photo = requests.get('https://imgs.xkcd.com/comics/python.png')
# print(photo)
with open('python.png','w') as pf:
    pf.write(photo.content)
    # print(pf)

    # curl -XGET "http://elasticsearch:9200/_cat/indices"

In [41]:
import requests
kibana = requests.get('http://localhost:9200/')
print(kibana)

<Response [200]>


In [38]:
# import datetime as dt
# ti =dt.date.fromtimestamp(1648065659252).strftime('%Y-%m-%d %H:%M:%S')
# print(ti)
import pandas as pd
pd.to_datetime(int('1648065659252'), utc=True, unit='ms')

Timestamp('2022-03-23 20:00:59.252000+0000', tz='UTC')

In [ ]:
data = [1,2,3,4,5,6,7]
temp = [d[1] for d in data]
print(temp)

In [4]:
import json

# JSON string:
# Multi-line string
x = """{
	"Name": "Jennifer Smith",
	"Contact Number": 7867567898,
	"Email": "jen123@gmail.com",
	"Hobbies":["Reading", "Sketching", "Horse Riding"]
	}"""

# parse x:
y = json.loads(x)

# the result is a Python dictionary:
print(y)


{'Name': 'Jennifer Smith', 'Contact Number': 7867567898, 'Email': 'jen123@gmail.com', 'Hobbies': ['Reading', 'Sketching', 'Horse Riding']}
